spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    username: opencve@gmail.com
    password: ftJp4tH8p79mFfU
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
