spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/demo_db2
    username: postgres
    password: 256487502

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    username: cvealert.v2@gmail.com
    password: ftJp4tH8p79mFfU
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
